export PROJECT_NAME=gamekit
export PROJECT_NAME_ALL_CAPITALIZED=GAMEKIT
export PROJECT_NAME_FIRST_CAPITALIZED=Gamekit

PROJECT_DIR=$(pwd)

export INCLUDE_DIR=${PROJECT_DIR}/include
export SOURCE_DIR=${PROJECT_DIR}/src
export TESTS_DIR=${PROJECT_DIR}/tests
export BUILD_DIR=${PROJECT_DIR}/build
export OUTPUT_DIR=${BUILD_DIR}/${PROJECT_NAME}
export TESTS_OUTPUT_DIR=${BUILD_DIR}/${PROJECT_NAME}-tests
export TEST_EXECUTABLE_NAME=${PROJECT_NAME}-tests
export TEST_EXECUTABLE_PATH=${TESTS_OUTPUT_DIR}/${TEST_EXECUTABLE_NAME}
export STATIC_LIBRARY_PATH=${BUILD_DIR}/lib${PROJECT_NAME}-static.a
export DYNAMIC_LIBRARY_PATH=${BUILD_DIR}/${PROJECT_NAME}/lib${PROJECT_NAME}.so

export CSHARP_DIR=${PROJECT_DIR}/csharp
export CSHARP_TEST_DIR=${CSHARP_DIR}/tests
export CSHARP_CSPROJ_PATH=${CSHARP_DIR}/${PROJECT_NAME_FIRST_CAPITALIZED}.Posix.csproj
export CSHARP_TEST_CSPROJ_PATH=${CSHARP_TEST_DIR}/${PROJECT_NAME_FIRST_CAPITALIZED}Tests.Posix.csproj
export CSHARP_OUTPUT_DIR=${BUILD_DIR}/${PROJECT_NAME}-csharp
export CSHARP_TEST_OUTPUT_DIR=${BUILD_DIR}/${PROJECT_NAME}-csharp-tests
