PROJECT_NAME=gamekit
PROJECT_NAME_ALL_CAPITALIZED=GAMEKIT
PROJECT_NAME_FIRST_CAPITALIZED=Gamekit

PROJECT_DIR=$(pwd)

INCLUDE_DIR=${PROJECT_DIR}/include
SOURCE_DIR=${PROJECT_DIR}/src
TESTS_DIR=${PROJECT_DIR}/tests
BUILD_DIR=${PROJECT_DIR}/build
OUTPUT_DIR=${BUILD_DIR}/${PROJECT_NAME}
TESTS_OUTPUT_DIR=${BUILD_DIR}/${PROJECT_NAME}-tests
TEST_EXECUTABLE_NAME=${PROJECT_NAME}-tests
TEST_EXECUTABLE_PATH=${TESTS_OUTPUT_DIR}/${TEST_EXECUTABLE_NAME}
STATIC_LIBRARY_PATH=${BUILD_DIR}/lib${PROJECT_NAME}-static.a
DYNAMIC_LIBRARY_PATH=${BUILD_DIR}/${PROJECT_NAME}/lib${PROJECT_NAME}.so

CSHARP_DIR=${PROJECT_DIR}/csharp
CSHARP_TEST_DIR=${CSHARP_DIR}/tests
CSHARP_CSPROJ_PATH=${CSHARP_DIR}/${PROJECT_NAME_FIRST_CAPITALIZED}.Posix.csproj
CSHARP_TEST_CSPROJ_PATH=${CSHARP_TEST_DIR}/${PROJECT_NAME_FIRST_CAPITALIZED}Tests.Posix.csproj
CSHARP_OUTPUT_DIR=${BUILD_DIR}/${PROJECT_NAME}-csharp
CSHARP_TEST_OUTPUT_DIR=${BUILD_DIR}/${PROJECT_NAME}-csharp-tests
