# -------------------------------
# Settings
# -------------------------------

set(GAMEKIT_SOURCE_DIR ${CMAKE_SOURCE_DIR}/src)
set(GAMEKIT_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/include)
set(GAMEKIT_TEST_DIR ${CMAKE_SOURCE_DIR}/tests)
set(GAMEKIT_API_EXPORT_VAR ${PROJECT_NAME_ALL_CAPITALIZED}_EXPORTS)
set(GAMEKIT_CSHARP_DIR ${CMAKE_SOURCE_DIR}/csharp)

if(WIN32)
	set(GAMEKIT_LIB_NAME ${PROJECT_NAME}.dll)
	set(GAMEKIT_CSHARP_PROJECT ${GAMEKIT_CSHARP_DIR}/${PROJECT_NAME_FIRST_CAPITALIZED}.Win64.csproj)
	set(GAMEKIT_CSHARP_TEST_PROJECT ${GAMEKIT_CSHARP_DIR}/tests/${PROJECT_NAME_FIRST_CAPITALIZED}Tests.Win64.csproj)
else()
	set(GAMEKIT_LIB_NAME lib${PROJECT_NAME}.so)
	set(GAMEKIT_CSHARP_PROJECT ${GAMEKIT_CSHARP_DIR}/${PROJECT_NAME_FIRST_CAPITALIZED}.Posix.csproj)
	set(GAMEKIT_CSHARP_TEST_PROJECT ${GAMEKIT_CSHARP_DIR}/tests/${PROJECT_NAME_FIRST_CAPITALIZED}Tests.Posix.csproj)
endif()

set(CMAKE_CXX_STANDARD 17)

message(STATUS "GAMEKIT_SOURCE_DIR = ${GAMEKIT_SOURCE_DIR}")
message(STATUS "GAMEKIT_INCLUDE_DIR = ${GAMEKIT_INCLUDE_DIR}")
message(STATUS "GAMEKIT_TEST_DIR = ${GAMEKIT_TEST_DIR}")
message(STATUS "GAMEKIT_API_EXPORT_VAR = ${GAMEKIT_API_EXPORT_VAR}")
message(STATUS "GAMEKIT_CSHARP_DIR = ${GAMEKIT_CSHARP_DIR}")
message(STATUS "GAMEKIT_LIB_NAME = ${GAMEKIT_LIB_NAME}")
message(STATUS "GAMEKIT_CSHARP_PROJECT = ${GAMEKIT_CSHARP_PROJECT}")
message(STATUS "GAMEKIT_CSHARP_TEST_PROJECT = ${GAMEKIT_CSHARP_TEST_PROJECT}")
message(STATUS "CMAKE_CXX_STANDARD = ${CMAKE_CXX_STANDARD}")
