# -------------------------------
# Settings
# -------------------------------

set(GAMEKIT_SOURCE_DIR ${CMAKE_SOURCE_DIR}/src)
set(GAMEKIT_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/include)
set(GAMEKIT_TEST_DIR ${CMAKE_SOURCE_DIR}/tests)
set(GAMEKIT_API_EXPORT_VAR ${PROJECT_NAME_ALL_CAPITALIZED}_EXPORTS)
set(GAMEKIT_CSHARP_DIR ${CMAKE_SOURCE_DIR}/csharp)
set(GAMEKIT_CSHARP_PROJECT_DIR ${GAMEKIT_CSHARP_DIR}/${PROJECT_NAME_FIRST_CAPITALIZED})
set(GAMEKIT_CSHARP_TEST_DIR ${GAMEKIT_CSHARP_DIR}/${PROJECT_NAME_FIRST_CAPITALIZED}Tests)

if(WIN32)
	set(GAMEKIT_LIB_NAME ${PROJECT_NAME}.dll)
else()
	set(GAMEKIT_LIB_NAME lib${PROJECT_NAME}.so)
endif()

set(CMAKE_CXX_STANDARD 17)
